name: List Football Competitions

on:
  workflow_dispatch:

jobs:
  list:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Tester les compétitions
        env:
          ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
        run: python list_sports.py
